//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connect.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Connect.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accounts.
        /// </summary>
        public static string AccountsTitle {
            get {
                return ResourceManager.GetString("AccountsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to done!.
        /// </summary>
        public static string AddTitle {
            get {
                return ResourceManager.GetString("AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Facebook.
        /// </summary>
        public static string AddToFacebookTitle {
            get {
                return ResourceManager.GetString("AddToFacebookTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to LinkedIn.
        /// </summary>
        public static string AddToLinkedinTitle {
            get {
                return ResourceManager.GetString("AddToLinkedinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email you entered is already in use.
        /// </summary>
        public static string alreadyUsedEmail {
            get {
                return ResourceManager.GetString("alreadyUsedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to done.
        /// </summary>
        public static string AppBarDoneButtonText {
            get {
                return ResourceManager.GetString("AppBarDoneButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login.
        /// </summary>
        public static string AppBarLoginButtonText {
            get {
                return ResourceManager.GetString("AppBarLoginButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logout.
        /// </summary>
        public static string AppBarLogoutButtonText {
            get {
                return ResourceManager.GetString("AppBarLogoutButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string AppBarSettingsButtonText {
            get {
                return ResourceManager.GetString("AppBarSettingsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY APPLICATION.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to logout?.
        /// </summary>
        public static string AreYouSureLogutTitle {
            get {
                return ResourceManager.GetString("AreYouSureLogutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to logout from Facebook?.
        /// </summary>
        public static string AreYouSureLogutTitleFacebook {
            get {
                return ResourceManager.GetString("AreYouSureLogutTitleFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to logout from LinkedIn?.
        /// </summary>
        public static string AreYouSureLogutTitleLinkedIn {
            get {
                return ResourceManager.GetString("AreYouSureLogutTitleLinkedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to initialize the camera.
        /// </summary>
        public static string CameraProblem {
            get {
                return ResourceManager.GetString("CameraProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to server.
        /// </summary>
        public static string ConnectingToServerTitle {
            get {
                return ResourceManager.GetString("ConnectingToServerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account.
        /// </summary>
        public static string CreateNewAccountTitle {
            get {
                return ResourceManager.GetString("CreateNewAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to whose email is.
        /// </summary>
        public static string done1 {
            get {
                return ResourceManager.GetString("done1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to just connected with you.
        /// </summary>
        public static string done2 {
            get {
                return ResourceManager.GetString("done2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tom Jones just shared with you his facebook and email address.  You are now friends in facebook and we&apos;ve sent him an email from you..
        /// </summary>
        public static string DoneMessage {
            get {
                return ResourceManager.GetString("DoneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to done!.
        /// </summary>
        public static string DoneTitle {
            get {
                return ResourceManager.GetString("DoneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al tratar de iniciar sesión en facebook..
        /// </summary>
        public static string FBLoginError {
            get {
                return ResourceManager.GetString("FBLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email.
        /// </summary>
        public static string invalidMail {
            get {
                return ResourceManager.GetString("invalidMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your name.
        /// </summary>
        public static string invalidName {
            get {
                return ResourceManager.GetString("invalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your password.
        /// </summary>
        public static string invalidPassword {
            get {
                return ResourceManager.GetString("invalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password should be at least 6 characters long.
        /// </summary>
        public static string invalidPassword1 {
            get {
                return ResourceManager.GetString("invalidPassword1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords don&apos;t match.
        /// </summary>
        public static string invalidReType {
            get {
                return ResourceManager.GetString("invalidReType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: The program will now open an external browser to reach Linkedin. Afterwards, you will have to close it to get back to the program. Do you wish to do it?.
        /// </summary>
        public static string LinkedinAmigo {
            get {
                return ResourceManager.GetString("LinkedinAmigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to facebook.
        /// </summary>
        public static string LoginToFacebookTitle {
            get {
                return ResourceManager.GetString("LoginToFacebookTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to LinkedIn.
        /// </summary>
        public static string LoginToLinkedinTitle {
            get {
                return ResourceManager.GetString("LoginToLinkedinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout from facebook.
        /// </summary>
        public static string LogoutFromFacebookTitle {
            get {
                return ResourceManager.GetString("LogoutFromFacebookTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout from linkedin.
        /// </summary>
        public static string LogoutFromLinkedInTitle {
            get {
                return ResourceManager.GetString("LogoutFromLinkedInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail.
        /// </summary>
        public static string MailTitle {
            get {
                return ResourceManager.GetString("MailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameTitle {
            get {
                return ResourceManager.GetString("NameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet connection.
        /// </summary>
        public static string NoInternetConnection {
            get {
                return ResourceManager.GetString("NoInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your WIFI or cellular data network and try again.
        /// </summary>
        public static string NoInternetConnectionMessage {
            get {
                return ResourceManager.GetString("NoInternetConnectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your registration could not be completed.Please check your WIFI or cellular data network and try again..
        /// </summary>
        public static string NoInternetConnectionMessageRegister {
            get {
                return ResourceManager.GetString("NoInternetConnectionMessageRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not authorized!.
        /// </summary>
        public static string notAuth {
            get {
                return ResourceManager.GetString("notAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The QR code does not correspond with any Connect&apos;s user!.
        /// </summary>
        public static string notFound {
            get {
                return ResourceManager.GetString("notFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string NoTitle {
            get {
                return ResourceManager.GetString("NoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string OkTitle {
            get {
                return ResourceManager.GetString("OkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordTitle {
            get {
                return ResourceManager.GetString("PasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to register.
        /// </summary>
        public static string RegisterTitle {
            get {
                return ResourceManager.GetString("RegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Type Password.
        /// </summary>
        public static string ReTypePasswordTitle {
            get {
                return ResourceManager.GetString("ReTypePasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not make friends with yourself.
        /// </summary>
        public static string sameID {
            get {
                return ResourceManager.GetString("sameID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        public static string Scan1Title {
            get {
                return ResourceManager.GetString("Scan1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing code.
        /// </summary>
        public static string scanning {
            get {
                return ResourceManager.GetString("scanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning.
        /// </summary>
        public static string ScanningTitle {
            get {
                return ResourceManager.GetString("ScanningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scan.
        /// </summary>
        public static string ScanTitle {
            get {
                return ResourceManager.GetString("ScanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string sdf {
            get {
                return ResourceManager.GetString("sdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR searching.
        /// </summary>
        public static string searching {
            get {
                return ResourceManager.GetString("searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string Share1Title {
            get {
                return ResourceManager.GetString("Share1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share.
        /// </summary>
        public static string ShareTitle {
            get {
                return ResourceManager.GetString("ShareTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user is not associated with a Facebook account.
        /// </summary>
        public static string withoutFace {
            get {
                return ResourceManager.GetString("withoutFace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user is not associated with a Linkedin account.
        /// </summary>
        public static string withoutLink {
            get {
                return ResourceManager.GetString("withoutLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email you entered is not correct.
        /// </summary>
        public static string WrongMailError {
            get {
                return ResourceManager.GetString("WrongMailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password you entered is not correct.
        /// </summary>
        public static string WrongPasswordError {
            get {
                return ResourceManager.GetString("WrongPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string YesTitle {
            get {
                return ResourceManager.GetString("YesTitle", resourceCulture);
            }
        }
    }
}
